sudo: required
language: java
jdk: openjdk11
branches:
  only:
  - master
  - "/v\\d+\\.\\d+[a-z]/"
script:
- mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mkdir $HOME/jars
- cp $HOME/build/vigneshse/chutes-and-ladder/target/*.jar $HOME/jars/chutes-and-ladders.jar
before_deploy:
- echo "Deploying jar file to S3"
deploy:
  provider: s3
  access_key_id: AKIA3MN3Z52KP2RWYKOY
  secret_access_key:
    secure: WgXU37wmqoLVogMsJ/EfDIndnUxrUKUSpApQFo2pKjzNqQ409f987MO/PKD04GmZhGgXCewQPb22Tex/GUK0vIRMIdb38uTpCvqxHPXy8viejAK70m3Bpq++fn8B52yDEHnKbEkUoCXnx8M6nLqhuYrDjHEznZDtQyhI0rEEH6i2i3OsBdRCWjrv4OcG1ZTy/P3sPy3aPqui4q0Lz9yhN3OZ/59W1Us3giEPcdKiSQpnCqqfA5pKW2JPcRaD024zv0T+ZZDIqrdGR5pitoqAdoOCLJPlG5yShhqtfnADJEIzGempl6k66xMuqYAGiKjFK2bkOTt7d7ebwXMEBdEbCbKGVe7YcfmOLn4CUE1XwH5cXJ64CMELEfJT/APa1xSYZ6Z6NHPvVAa80JHRYtxv2F7M2iAbmBpauEdAh3/JlBrAk9sBqJjFq+uLPeM5Y1dDOHhsQzjV5OrwCnO+2E8W3p7jYUHr5gr4ZwKd28tV7qg3tfTJlmc+Xtv69Cq2Dun9sWb/8jWLOx7m5GJbt9RvuUOm3NkB+iFzXuF2MXoo2AhweWJuPUU0GHArWJwxdAnHShie8FpFWQrh3IRu4X0uQ8RDMQF8aclcGMkWpRw8wqfV+3WlG+i5aOFH5jk37Mp0nK78YRtERQ6ud4fB382Q9AYhRbVuwL/co0YZJEbh+/8=
  bucket: "vigneshse"
  region: us-west-2
  local-dir: $HOME/jars
  acl: public_read
  on:
    repo: vigneshse/chutes-and-ladder
